### ISSUE TITLE
ERROR: undefined symbol: _ZN8octomath6Pose6DC1ERKS0_

### ISSUE THREAD

**Issue by cir2001** [ADVRHumanoids/OpenSoT#218]
Hi,
I am trying to use OpenSoT under Python. I have already installed OpenSoT. When executing the code in bindings/python/examples/panda_ik.py, the following error occurs. How should I solve it?

Exception has occurred: ImportError
/opt/ros/noetic/lib/x86_64-linux-gnu/libfcl.so.0.6: undefined symbol: _ZN8octomath6Pose6DC1ERKS0_
  File "/home/cir/test/t1.py", line 5, in <module>
    from pyopensot.tasks.velocity import Postural, Cartesian, Manipulability, MinimumEffort
ImportError: /opt/ros/noetic/lib/x86_64-linux-gnu/libfcl.so.0.6: undefined symbol: _ZN8octomath6Pose6DC1ERKS0_

**Comment by EnricoMingo** [comment]
Hi @cir2001, looks like you are linking against libfcl in ROS Noetic. We do not use it anymore in OpenSoT, instead we link against hpp-fcl. Please give a look at [this DockerFile](https://github.com/hucebot/opensot_docker/blob/master/Dockerfile) for the installations packages.  Another point is, which branch are you using of OpenSoT? Please use the last `4.0-devel`.

**Comment by cir2001** [comment]
Hi @EnricoMingo, thank you very much, I will try the DockerFile for the installation packages.
